# stage 1
# Build stage with explicit platform specification
#FROM ghcr.io/astral-sh/uv:python3.13-alpine AS uv

FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/uv:python3.13-alpine-arm64 AS uv

# Install the project into /app
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
ADD . /app
RUN uv sync --frozen --no-dev --no-editable


# stage 2
#FROM docker.m.daocloud.io/python:3.13-alpine

FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/python:3.13-alpine-timezone-arm64

COPY --from=uv --chown=app:app /app/.venv /app/.venv

RUN apk add curl

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT ["celery-httpserver", "--port", "8000"]