# stage 1
# Build stage with explicit platform specification
#FROM ghcr.io/astral-sh/uv:python3.13-alpine AS uv

FROM ghcr.io/astral-sh/uv:python3.13-alpine AS uv

RUN apk add --no-cache build-base cargo openssl-dev

# Install the project into /app
WORKDIR /app

RUN mkdir /app/sdks

COPY sdks/model_sdk-0.2.0-py3-none-any.whl /app/sdks/model_sdk-0.2.0-py3-none-any.whl

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
ADD . /app
RUN uv sync --frozen --no-dev --no-editable


# stage 2

FROM python:3.13-alpine

RUN apk add --no-cache tzdata && \
    ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime && \
    echo "America/New_York" > /etc/timezone
ENV TZ="America/New_York"

COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

COPY agent_card /app/agent_card

RUN rm -fr /app/.venv/lib/python3.13/site-packages/a2a/utils/telemetry.py

COPY telemetry.py /app/.venv/lib/python3.13/site-packages/a2a/utils/telemetry.py

ENTRYPOINT ["routing-agent", "--port", "10100"]
