FROM python:3.13

RUN apt update

RUN apt install -y vim curl

COPY requirements.txt /tmp

RUN pip3 install -r /tmp/requirements.txt -i https://pypi.org/simple

RUN mkdir /app

WORKDIR /app

ADD . /app
