{{- if and .Values.mysql.enabled (not .Values.mysql.external.host) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dac.mysql.serviceName" . }}
  labels:
    {{- include "dac.componentLabels" (dict "context" . "name" "mysql") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}
      targetPort: 3306
  selector:
    {{- include "dac.selectorLabels" (dict "context" . "name" "mysql") | nindent 4 }}
{{- end }}
