apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-production-fewshots
  namespace: default
  labels:
    app.kubernetes.io/name: execution-engine
    data-source: dd-0
data:
  fewshots.json: |
    [
      {
        "query": "查找年龄大于30岁的用户",
        "answer": "SELECT name, age FROM users WHERE age > 30"
      },
      {
        "query": "统计最近7天注册的用户数量",
        "answer": "SELECT COUNT(*) FROM users WHERE registration_date >= DATE_SUB(NOW(), INTERVAL 7 DAY)"
      },
      {
        "query": "农商银行总行2024年零售存款的总额是多少",
        "answer": "SELECT retail_deposit_total FROM deposit_data WHERE branch_name = '农商银行总行' AND data_date = '2024-12-31'" 
      }
    ]
  background_knowledge.json: |
    [
      {
        "description": "年度总额采用年末值进行处理。举例来说，如果想知道2023年的贷款总额，只需要查询2023年的记录中，看看月份最大的那个月的数据就是2023年的贷款总额。"
      }
    ]

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: bank-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "dactest"
      extract:
        tables: []
      prompts:
        prompts:
          name: "mysql-production-fewshots"
  syncPolicy:
    enabled: true
    schedule: "10m"

---


apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dianshang-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "test1"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""


---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: user-management-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "user_management"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""

---


apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: product-management-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "product_management"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: order-management-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "order_management"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""


---


apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: customer-service-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "customer_service"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: inventory-warehouse-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "inventory_warehouse"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""


---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: marketing-promotion-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "marketing_promotion"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""


---


apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: supply-chain-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "supply_chain"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""


---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd01-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "test1"
      codeRepo:
        codeRepoType: "github"
        codeRepoPath: "https://github.com/James-Dao/test-code"
        codeRepoBranch: "main"
        codeRepoToken: ""
      extract:
        tables: []
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd01-github-00001
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: github
      name: "github-00001"
      metadata:
        codeRepoPath: "https://github.com/James-Dao/test-code.git"
        codeRepoBranch: "main"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""
      
---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd01-gitee-nmap
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: gitee
      name: "gitee-nmap"
      metadata:
        codeRepoPath: "https://gitee.com/tan_fu_xiang/nmap.git"
        codeRepoBranch: "master"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: datatunerx
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: gitee
      name: "gitee-datatunerx"
      metadata:
        codeRepoPath: "https://gitee.com/jamesxiong888/datatunerx.git"
        codeRepoBranch: "main"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""


apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: metaserver
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: gitee
      name: "gitee-metaserver"
      metadata:
        codeRepoPath: "https://gitee.com/jamesxiong888/meta-server.git"
        codeRepoBranch: "main"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dianshang-code
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: gitee
      name: "dianshang-code"
      metadata:
        codeRepoPath: "https://gitee.com/jamesxiong888/test-code.git"
        codeRepoBranch: "main"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd-postgres
  namespace: default
spec:
  descriptorType: "structured-postgres"
  sources:
    - type: postgres
      name: "postgres-production"
      metadata:
        host: "postgres-server"
        port: "3306"
        user: "root"
        password: "123"
        database: "dactest"
      extract:
        tables: ["deposit_data", "balance_sheet", "loan_data", "retail_loan_detail"]
      prompts:
        prompts:
          name: "postgres-production-fewshots"


---
apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: minio-dianshang
  namespace: default
spec:
  descriptorType: "unstructured"
  sources:
    - type: minio
      name: "minio-dianshang"
      metadata:
        host: "minio-server.dac:9000"
        access_key: "minioadmin"
        secret_key: "minioadmin"
        bucket: "dactest"
      extract:
        files: ["dianshang.docx"]
      prompts:
        prompts:
          name: ""

---
apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: minio-satellite
  namespace: default
spec:
  descriptorType: "unstructured"
  sources:
    - type: minio
      name: "minio-satellite"
      metadata:
        host: "minio-server.dac:9000"
        access_key: "minioadmin"
        secret_key: "minioadmin"
        bucket: "dactest"
      extract:
        files: ["naive.pdf"]
      prompts:
        prompts:
          name: ""
    
---
apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd-fileserver-test
  namespace: default
spec:
  descriptorType: "unstructured"
  sources:
    - type: fileserver
      name: "fileserver-production"
      metadata:
        host: "fileserver-server"
        port: "8000"
      extract:
        files: ["test.pdf"]
      prompts:
        prompts:
          name: ""



---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dianshang-mysql
  namespace: default
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server.dac"
        port: "3306"
        user: "root"
        password: "123"
        database: "test1"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""
  syncPolicy:
    enabled: true
    schedule: "3m"

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dianshang-code
  namespace: default
spec:
  descriptorType: "code"
  sources:
    - type: gitee
      name: "dianshang-code"
      metadata:
        codeRepoPath: "https://gitee.com/jamesxiong888/test-code.git"
        codeRepoBranch: "main"
        codeRepoToken: ""
      prompts:
        prompts:
          name: ""
  syncPolicy:
    enabled: true
    schedule: "5m"

---

apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dianshang-file
  namespace: default
spec:
  descriptorType: "unstructured"
  sources:
    - type: minio
      name: "dianshang-file"
      metadata:
        host: "minio-server.dac:9000"
        access_key: "minioadmin"
        secret_key: "minioadmin"
        bucket: "dactest"
      extract:
        files: ["dianshang.docx"]
      prompts:
        prompts:
          name: ""
  syncPolicy:
    enabled: true
    schedule: "5m"

