// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Run is the predicate function for run builders.
type Run func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
