{{- if .Values.executionEngine.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dac-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dac.componentLabels" (dict "context" . "name" "execution-engine") | nindent 4 }}
data:
  {{- with .Values.executionEngine.dacConfig }}
  {{- if .observationBaseUrl }}
  observation-base-url: {{ .observationBaseUrl | quote }}
  {{- end }}
  {{- if .observationSecretKey }}
  observation-secret-key: {{ .observationSecretKey | quote }}
  {{- end }}
  {{- if .observationPublicKey }}
  observation-public-key: {{ .observationPublicKey | quote }}
  {{- end }}
  {{- end }}
  redis-host: {{ printf "%s.%s.svc.cluster.local" (include "dac.redis.serviceName" .) .Release.Namespace | quote }}
  redis-port: {{ .Values.redis.port | default "6379" | quote }}
  redis-password: {{ .Values.redis.password | default "123" | quote }}
  data-services-url: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "dac.dataServices.serviceName" .) .Release.Namespace (.Values.dataServices.service.port | default 8000) | quote }}
  biz-orchestrator-agent-registry: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "dac.bizOrchestratorRegistry.serviceName" .) .Release.Namespace (.Values.bizOrchestratorRegistry.service.port | default 8000) | quote }}
  orchestrator-agent-registry: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "dac.orchestratorRegistry.serviceName" .) .Release.Namespace (.Values.orchestratorRegistry.service.port | default 8000) | quote }}
  orchestrator-agent-image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" "orchestrator-agent" "tag" .Values.executionEngine.agentImages.orchestratorAgent.tag) | quote }}
  expert-agent-image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" "expert-agent" "tag" .Values.executionEngine.agentImages.expertAgent.tag) | quote }}
  ds-data-services-image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" "dac-data-services" "tag" .Values.executionEngine.agentImages.dacDataServices.tag) | quote }}
  code-agent-image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" "code-agent" "tag" .Values.executionEngine.agentImages.codeAgent.tag) | quote }}
  doc-agent-image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" "doc-agent" "tag" .Values.executionEngine.agentImages.docAgent.tag) | quote }}
  default-planner-llm: {{ .Values.executionEngine.dacConfig.defaultPlannerLLM | default "llm-default" | quote }}
  default-expert-llm: {{ .Values.executionEngine.dacConfig.defaultExpertLLM | default "llm-default" | quote }}
{{- end }}
