{{- if .Values.orchestratorRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dac.orchestratorRegistry.serviceName" . }}
  labels:
    {{- include "dac.componentLabels" (dict "context" . "name" "orchestrator-registry") | nindent 4 }}
spec:
  replicas: {{ .Values.orchestratorRegistry.replicas }}
  selector:
    matchLabels:
      {{- include "dac.selectorLabels" (dict "context" . "name" "orchestrator-registry") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dac.selectorLabels" (dict "context" . "name" "orchestrator-registry") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator-registry
          image: {{ include "dac.image" (dict "registry" .Values.global.imageRegistry "repository" .Values.orchestratorRegistry.image.repository "tag" .Values.orchestratorRegistry.image.tag) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.orchestratorRegistry.service.targetPort }}
          env:
            - name: DATA_SERVICES
              value: {{ include "dac.dataServices.url" . | quote }}
            - name: COLLECTION_NAME
              value: {{ .Values.orchestratorRegistry.config.collectionName | quote }}
          args:
            - "--redis-host"
            - {{ include "dac.redis.serviceName" . | quote }}
            - "--redis-port"
            - {{ .Values.redis.port | quote }}
            - "--redis-db"
            - {{ .Values.orchestratorRegistry.config.redisDb | quote }}
            - "--password"
            - {{ .Values.redis.password | quote }}
          resources:
            {{- toYaml .Values.orchestratorRegistry.resources | nindent 12 }}
{{- end }}
