{{- if and .Values.tdb.enabled (not .Values.tdb.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dac.tdb.serviceName" . }}
  labels:
    {{- include "dac.componentLabels" (dict "context" . "name" "tdb") | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "dac.tdb.databaseURL" . | quote }}
  PGPASSWORD: {{ include "dac.tdb.databasePassword" . | quote }}
{{- end }}
