FROM python:3.12

RUN apt update

RUN apt install -y vim curl libglib2.0-0 libgl1-mesa-dev

# Install mineru latest
RUN python3 -m pip install -U 'mineru[core]'

# Download models and update the configuration file
RUN /bin/bash -c "mineru-models-download -s huggingface -m pipeline"

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime && \
    echo "America/New_York" > /etc/timezone && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TZ="America/New_York"

COPY requirements.txt /tmp

RUN pip3 install -r /tmp/requirements.txt

WORKDIR /app

COPY nltk_data /root/nltk_data

ADD . /app

RUN pip3 install /app/sdks/model_sdk-0.2.0-py3-none-any.whl

COPY entrypoint-job.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]