FROM python:3.12

RUN apt update

RUN apt install -y vim curl libglib2.0-0 libgl1-mesa-dev

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TZ="Asia/Shanghai"
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /tmp

RUN pip3 install -r /tmp/requirements.txt -i https://pypi.org/simple

WORKDIR /app

ADD . /app

COPY entrypoint-observer.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]
