FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/python:3.12-arm64

# if you located in China, you can use aliyun mirror to speed up
RUN sed -i 's@deb.debian.org@mirrors.aliyun.com@g' /etc/apt/sources.list.d/debian.sources

RUN apt update

RUN apt install -y vim curl libglib2.0-0 libgl1-mesa-dev

# Install mineru latest
RUN python3 -m pip install -U 'mineru[core]' -i https://pypi.tuna.tsinghua.edu.cn/simple

# Download models and update the configuration file
RUN /bin/bash -c "mineru-models-download -s modelscope -m pipeline"

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TZ="Asia/Shanghai"

COPY requirements.txt /tmp

RUN pip3 install -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app

COPY nltk_data /root/nltk_data

ADD . /app

RUN pip3 install /app/sdks/model_sdk-0.1.0-py3-none-any.whl -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY entrypoint-worker.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]