// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/discoveryjob"
	"github.com/lvyanru/dac-apiserver/internal/ent/schema"
)

// DiscoveryJobCreate is the builder for creating a DiscoveryJob entity.
type DiscoveryJobCreate struct {
	config
	mutation *DiscoveryJobMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *DiscoveryJobCreate) SetName(v string) *DiscoveryJobCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableName(v *string) *DiscoveryJobCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *DiscoveryJobCreate) SetTarget(v string) *DiscoveryJobCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetPortsSpec sets the "ports_spec" field.
func (_c *DiscoveryJobCreate) SetPortsSpec(v string) *DiscoveryJobCreate {
	_c.mutation.SetPortsSpec(v)
	return _c
}

// SetNillablePortsSpec sets the "ports_spec" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillablePortsSpec(v *string) *DiscoveryJobCreate {
	if v != nil {
		_c.SetPortsSpec(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DiscoveryJobCreate) SetStatus(v string) *DiscoveryJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableStatus(v *string) *DiscoveryJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *DiscoveryJobCreate) SetError(v string) *DiscoveryJobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableError(v *string) *DiscoveryJobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DiscoveryJobCreate) SetStartedAt(v time.Time) *DiscoveryJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableStartedAt(v *time.Time) *DiscoveryJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *DiscoveryJobCreate) SetFinishedAt(v time.Time) *DiscoveryJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableFinishedAt(v *time.Time) *DiscoveryJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetServices sets the "services" field.
func (_c *DiscoveryJobCreate) SetServices(v []schema.DiscoveryService) *DiscoveryJobCreate {
	_c.mutation.SetServices(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiscoveryJobCreate) SetCreatedAt(v time.Time) *DiscoveryJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableCreatedAt(v *time.Time) *DiscoveryJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DiscoveryJobCreate) SetUpdatedAt(v time.Time) *DiscoveryJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableUpdatedAt(v *time.Time) *DiscoveryJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DiscoveryJobCreate) SetID(v uuid.UUID) *DiscoveryJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DiscoveryJobCreate) SetNillableID(v *uuid.UUID) *DiscoveryJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DiscoveryJobMutation object of the builder.
func (_c *DiscoveryJobCreate) Mutation() *DiscoveryJobMutation {
	return _c.mutation
}

// Save creates the DiscoveryJob in the database.
func (_c *DiscoveryJobCreate) Save(ctx context.Context) (*DiscoveryJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscoveryJobCreate) SaveX(ctx context.Context) *DiscoveryJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveryJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveryJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscoveryJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := discoveryjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := discoveryjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := discoveryjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := discoveryjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscoveryJobCreate) check() error {
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "DiscoveryJob.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := discoveryjob.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "DiscoveryJob.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DiscoveryJob.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiscoveryJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DiscoveryJob.updated_at"`)}
	}
	return nil
}

func (_c *DiscoveryJobCreate) sqlSave(ctx context.Context) (*DiscoveryJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscoveryJobCreate) createSpec() (*DiscoveryJob, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscoveryJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discoveryjob.Table, sqlgraph.NewFieldSpec(discoveryjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(discoveryjob.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(discoveryjob.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.PortsSpec(); ok {
		_spec.SetField(discoveryjob.FieldPortsSpec, field.TypeString, value)
		_node.PortsSpec = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(discoveryjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(discoveryjob.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(discoveryjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(discoveryjob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.Services(); ok {
		_spec.SetField(discoveryjob.FieldServices, field.TypeJSON, value)
		_node.Services = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(discoveryjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(discoveryjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DiscoveryJobCreateBulk is the builder for creating many DiscoveryJob entities in bulk.
type DiscoveryJobCreateBulk struct {
	config
	err      error
	builders []*DiscoveryJobCreate
}

// Save creates the DiscoveryJob entities in the database.
func (_c *DiscoveryJobCreateBulk) Save(ctx context.Context) ([]*DiscoveryJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscoveryJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscoveryJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscoveryJobCreateBulk) SaveX(ctx context.Context) []*DiscoveryJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveryJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveryJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
