// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/discoveryjob"
	"github.com/lvyanru/dac-apiserver/internal/ent/schema"
)

// DiscoveryJob is the model entity for the DiscoveryJob schema.
type DiscoveryJob struct {
	config `json:"-"`
	// ID of the ent.
	// 扫描任务ID
	ID uuid.UUID `json:"id,omitempty"`
	// 用户自定义名称
	Name string `json:"name,omitempty"`
	// 扫描目标（IP/Host）
	Target string `json:"target,omitempty"`
	// 端口范围输入（原始字符串）
	PortsSpec string `json:"ports_spec,omitempty"`
	// 任务状态
	Status string `json:"status,omitempty"`
	// 失败原因
	Error string `json:"error,omitempty"`
	// 开始时间
	StartedAt *time.Time `json:"started_at,omitempty"`
	// 结束时间
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// 扫描结果（服务列表）
	Services []schema.DiscoveryService `json:"services,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscoveryJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discoveryjob.FieldServices:
			values[i] = new([]byte)
		case discoveryjob.FieldName, discoveryjob.FieldTarget, discoveryjob.FieldPortsSpec, discoveryjob.FieldStatus, discoveryjob.FieldError:
			values[i] = new(sql.NullString)
		case discoveryjob.FieldStartedAt, discoveryjob.FieldFinishedAt, discoveryjob.FieldCreatedAt, discoveryjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case discoveryjob.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscoveryJob fields.
func (_m *DiscoveryJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discoveryjob.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case discoveryjob.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case discoveryjob.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case discoveryjob.FieldPortsSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ports_spec", values[i])
			} else if value.Valid {
				_m.PortsSpec = value.String
			}
		case discoveryjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case discoveryjob.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case discoveryjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case discoveryjob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case discoveryjob.FieldServices:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field services", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Services); err != nil {
					return fmt.Errorf("unmarshal field services: %w", err)
				}
			}
		case discoveryjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case discoveryjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscoveryJob.
// This includes values selected through modifiers, order, etc.
func (_m *DiscoveryJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DiscoveryJob.
// Note that you need to call DiscoveryJob.Unwrap() before calling this method if this DiscoveryJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscoveryJob) Update() *DiscoveryJobUpdateOne {
	return NewDiscoveryJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscoveryJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscoveryJob) Unwrap() *DiscoveryJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscoveryJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscoveryJob) String() string {
	var builder strings.Builder
	builder.WriteString("DiscoveryJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("ports_spec=")
	builder.WriteString(_m.PortsSpec)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("services=")
	builder.WriteString(fmt.Sprintf("%v", _m.Services))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DiscoveryJobs is a parsable slice of DiscoveryJob.
type DiscoveryJobs []*DiscoveryJob
