// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrolepermission"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
)

// PlatformRolePermissionDelete is the builder for deleting a PlatformRolePermission entity.
type PlatformRolePermissionDelete struct {
	config
	hooks    []Hook
	mutation *PlatformRolePermissionMutation
}

// Where appends a list predicates to the PlatformRolePermissionDelete builder.
func (_d *PlatformRolePermissionDelete) Where(ps ...predicate.PlatformRolePermission) *PlatformRolePermissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PlatformRolePermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformRolePermissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PlatformRolePermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(platformrolepermission.Table, sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PlatformRolePermissionDeleteOne is the builder for deleting a single PlatformRolePermission entity.
type PlatformRolePermissionDeleteOne struct {
	_d *PlatformRolePermissionDelete
}

// Where appends a list predicates to the PlatformRolePermissionDelete builder.
func (_d *PlatformRolePermissionDeleteOne) Where(ps ...predicate.PlatformRolePermission) *PlatformRolePermissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PlatformRolePermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{platformrolepermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PlatformRolePermissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
