// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrolepermission"
)

// PlatformRolePermissionCreate is the builder for creating a PlatformRolePermission entity.
type PlatformRolePermissionCreate struct {
	config
	mutation *PlatformRolePermissionMutation
	hooks    []Hook
}

// SetRoleID sets the "role_id" field.
func (_c *PlatformRolePermissionCreate) SetRoleID(v uuid.UUID) *PlatformRolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *PlatformRolePermissionCreate) SetPermissionID(v uuid.UUID) *PlatformRolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformRolePermissionCreate) SetCreatedAt(v time.Time) *PlatformRolePermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformRolePermissionCreate) SetNillableCreatedAt(v *time.Time) *PlatformRolePermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlatformRolePermissionCreate) SetID(v uuid.UUID) *PlatformRolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlatformRolePermissionCreate) SetNillableID(v *uuid.UUID) *PlatformRolePermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRole sets the "role" edge to the PlatformRole entity.
func (_c *PlatformRolePermissionCreate) SetRole(v *PlatformRole) *PlatformRolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the PlatformRolePermissionMutation object of the builder.
func (_c *PlatformRolePermissionCreate) Mutation() *PlatformRolePermissionMutation {
	return _c.mutation
}

// Save creates the PlatformRolePermission in the database.
func (_c *PlatformRolePermissionCreate) Save(ctx context.Context) (*PlatformRolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformRolePermissionCreate) SaveX(ctx context.Context) *PlatformRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformRolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformRolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformRolePermissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platformrolepermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := platformrolepermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformRolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "PlatformRolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "PlatformRolePermission.permission_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PlatformRolePermission.created_at"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "PlatformRolePermission.role"`)}
	}
	return nil
}

func (_c *PlatformRolePermissionCreate) sqlSave(ctx context.Context) (*PlatformRolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformRolePermissionCreate) createSpec() (*PlatformRolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformRolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformrolepermission.Table, sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(platformrolepermission.FieldPermissionID, field.TypeUUID, value)
		_node.PermissionID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platformrolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformrolepermission.RoleTable,
			Columns: []string{platformrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlatformRolePermissionCreateBulk is the builder for creating many PlatformRolePermission entities in bulk.
type PlatformRolePermissionCreateBulk struct {
	config
	err      error
	builders []*PlatformRolePermissionCreate
}

// Save creates the PlatformRolePermission entities in the database.
func (_c *PlatformRolePermissionCreateBulk) Save(ctx context.Context) ([]*PlatformRolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformRolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformRolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformRolePermissionCreateBulk) SaveX(ctx context.Context) []*PlatformRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformRolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformRolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
