// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformuserrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
)

// PlatformUserRoleUpdate is the builder for updating PlatformUserRole entities.
type PlatformUserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformUserRoleMutation
}

// Where appends a list predicates to the PlatformUserRoleUpdate builder.
func (_u *PlatformUserRoleUpdate) Where(ps ...predicate.PlatformUserRole) *PlatformUserRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PlatformUserRoleUpdate) SetUserID(v uuid.UUID) *PlatformUserRoleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PlatformUserRoleUpdate) SetNillableUserID(v *uuid.UUID) *PlatformUserRoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *PlatformUserRoleUpdate) SetRoleID(v uuid.UUID) *PlatformUserRoleUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PlatformUserRoleUpdate) SetNillableRoleID(v *uuid.UUID) *PlatformUserRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the PlatformRole entity.
func (_u *PlatformUserRoleUpdate) SetRole(v *PlatformRole) *PlatformUserRoleUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PlatformUserRoleMutation object of the builder.
func (_u *PlatformUserRoleUpdate) Mutation() *PlatformUserRoleMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the PlatformRole entity.
func (_u *PlatformUserRoleUpdate) ClearRole() *PlatformUserRoleUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformUserRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformUserRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUserRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUserRoleUpdate) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlatformUserRole.role"`)
	}
	return nil
}

func (_u *PlatformUserRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformuserrole.Table, platformuserrole.Columns, sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(platformuserrole.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformuserrole.RoleTable,
			Columns: []string{platformuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformuserrole.RoleTable,
			Columns: []string{platformuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformUserRoleUpdateOne is the builder for updating a single PlatformUserRole entity.
type PlatformUserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformUserRoleMutation
}

// SetUserID sets the "user_id" field.
func (_u *PlatformUserRoleUpdateOne) SetUserID(v uuid.UUID) *PlatformUserRoleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PlatformUserRoleUpdateOne) SetNillableUserID(v *uuid.UUID) *PlatformUserRoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *PlatformUserRoleUpdateOne) SetRoleID(v uuid.UUID) *PlatformUserRoleUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PlatformUserRoleUpdateOne) SetNillableRoleID(v *uuid.UUID) *PlatformUserRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the PlatformRole entity.
func (_u *PlatformUserRoleUpdateOne) SetRole(v *PlatformRole) *PlatformUserRoleUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PlatformUserRoleMutation object of the builder.
func (_u *PlatformUserRoleUpdateOne) Mutation() *PlatformUserRoleMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the PlatformRole entity.
func (_u *PlatformUserRoleUpdateOne) ClearRole() *PlatformUserRoleUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the PlatformUserRoleUpdate builder.
func (_u *PlatformUserRoleUpdateOne) Where(ps ...predicate.PlatformUserRole) *PlatformUserRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformUserRoleUpdateOne) Select(field string, fields ...string) *PlatformUserRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlatformUserRole entity.
func (_u *PlatformUserRoleUpdateOne) Save(ctx context.Context) (*PlatformUserRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUserRoleUpdateOne) SaveX(ctx context.Context) *PlatformUserRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformUserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUserRoleUpdateOne) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlatformUserRole.role"`)
	}
	return nil
}

func (_u *PlatformUserRoleUpdateOne) sqlSave(ctx context.Context) (_node *PlatformUserRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformuserrole.Table, platformuserrole.Columns, sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlatformUserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformuserrole.FieldID)
		for _, f := range fields {
			if !platformuserrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platformuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(platformuserrole.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformuserrole.RoleTable,
			Columns: []string{platformuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformuserrole.RoleTable,
			Columns: []string{platformuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlatformUserRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
