// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrolepermission"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformuserrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
)

// PlatformRoleUpdate is the builder for updating PlatformRole entities.
type PlatformRoleUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformRoleMutation
}

// Where appends a list predicates to the PlatformRoleUpdate builder.
func (_u *PlatformRoleUpdate) Where(ps ...predicate.PlatformRole) *PlatformRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *PlatformRoleUpdate) SetCode(v string) *PlatformRoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlatformRoleUpdate) SetNillableCode(v *string) *PlatformRoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformRoleUpdate) SetName(v string) *PlatformRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformRoleUpdate) SetNillableName(v *string) *PlatformRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsSuper sets the "is_super" field.
func (_u *PlatformRoleUpdate) SetIsSuper(v bool) *PlatformRoleUpdate {
	_u.mutation.SetIsSuper(v)
	return _u
}

// SetNillableIsSuper sets the "is_super" field if the given value is not nil.
func (_u *PlatformRoleUpdate) SetNillableIsSuper(v *bool) *PlatformRoleUpdate {
	if v != nil {
		_u.SetIsSuper(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlatformRoleUpdate) SetDescription(v string) *PlatformRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlatformRoleUpdate) SetNillableDescription(v *string) *PlatformRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlatformRoleUpdate) ClearDescription() *PlatformRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformRoleUpdate) SetUpdatedAt(v time.Time) *PlatformRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the PlatformRolePermission entity by IDs.
func (_u *PlatformRoleUpdate) AddPermissionIDs(ids ...uuid.UUID) *PlatformRoleUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the PlatformRolePermission entity.
func (_u *PlatformRoleUpdate) AddPermissions(v ...*PlatformRolePermission) *PlatformRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserIDs adds the "users" edge to the PlatformUserRole entity by IDs.
func (_u *PlatformRoleUpdate) AddUserIDs(ids ...uuid.UUID) *PlatformRoleUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the PlatformUserRole entity.
func (_u *PlatformRoleUpdate) AddUsers(v ...*PlatformUserRole) *PlatformRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the PlatformRoleMutation object of the builder.
func (_u *PlatformRoleUpdate) Mutation() *PlatformRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the PlatformRolePermission entity.
func (_u *PlatformRoleUpdate) ClearPermissions() *PlatformRoleUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to PlatformRolePermission entities by IDs.
func (_u *PlatformRoleUpdate) RemovePermissionIDs(ids ...uuid.UUID) *PlatformRoleUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to PlatformRolePermission entities.
func (_u *PlatformRoleUpdate) RemovePermissions(v ...*PlatformRolePermission) *PlatformRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUsers clears all "users" edges to the PlatformUserRole entity.
func (_u *PlatformRoleUpdate) ClearUsers() *PlatformRoleUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to PlatformUserRole entities by IDs.
func (_u *PlatformRoleUpdate) RemoveUserIDs(ids ...uuid.UUID) *PlatformRoleUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to PlatformUserRole entities.
func (_u *PlatformRoleUpdate) RemoveUsers(v ...*PlatformUserRole) *PlatformRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformRoleUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := platformrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PlatformRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := platformrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlatformRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformrole.Table, platformrole.Columns, sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(platformrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platformrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuper(); ok {
		_spec.SetField(platformrole.FieldIsSuper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(platformrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(platformrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformRoleUpdateOne is the builder for updating a single PlatformRole entity.
type PlatformRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformRoleMutation
}

// SetCode sets the "code" field.
func (_u *PlatformRoleUpdateOne) SetCode(v string) *PlatformRoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlatformRoleUpdateOne) SetNillableCode(v *string) *PlatformRoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformRoleUpdateOne) SetName(v string) *PlatformRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformRoleUpdateOne) SetNillableName(v *string) *PlatformRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsSuper sets the "is_super" field.
func (_u *PlatformRoleUpdateOne) SetIsSuper(v bool) *PlatformRoleUpdateOne {
	_u.mutation.SetIsSuper(v)
	return _u
}

// SetNillableIsSuper sets the "is_super" field if the given value is not nil.
func (_u *PlatformRoleUpdateOne) SetNillableIsSuper(v *bool) *PlatformRoleUpdateOne {
	if v != nil {
		_u.SetIsSuper(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlatformRoleUpdateOne) SetDescription(v string) *PlatformRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlatformRoleUpdateOne) SetNillableDescription(v *string) *PlatformRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlatformRoleUpdateOne) ClearDescription() *PlatformRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformRoleUpdateOne) SetUpdatedAt(v time.Time) *PlatformRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the PlatformRolePermission entity by IDs.
func (_u *PlatformRoleUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *PlatformRoleUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the PlatformRolePermission entity.
func (_u *PlatformRoleUpdateOne) AddPermissions(v ...*PlatformRolePermission) *PlatformRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserIDs adds the "users" edge to the PlatformUserRole entity by IDs.
func (_u *PlatformRoleUpdateOne) AddUserIDs(ids ...uuid.UUID) *PlatformRoleUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the PlatformUserRole entity.
func (_u *PlatformRoleUpdateOne) AddUsers(v ...*PlatformUserRole) *PlatformRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the PlatformRoleMutation object of the builder.
func (_u *PlatformRoleUpdateOne) Mutation() *PlatformRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the PlatformRolePermission entity.
func (_u *PlatformRoleUpdateOne) ClearPermissions() *PlatformRoleUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to PlatformRolePermission entities by IDs.
func (_u *PlatformRoleUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *PlatformRoleUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to PlatformRolePermission entities.
func (_u *PlatformRoleUpdateOne) RemovePermissions(v ...*PlatformRolePermission) *PlatformRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUsers clears all "users" edges to the PlatformUserRole entity.
func (_u *PlatformRoleUpdateOne) ClearUsers() *PlatformRoleUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to PlatformUserRole entities by IDs.
func (_u *PlatformRoleUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *PlatformRoleUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to PlatformUserRole entities.
func (_u *PlatformRoleUpdateOne) RemoveUsers(v ...*PlatformUserRole) *PlatformRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the PlatformRoleUpdate builder.
func (_u *PlatformRoleUpdateOne) Where(ps ...predicate.PlatformRole) *PlatformRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformRoleUpdateOne) Select(field string, fields ...string) *PlatformRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlatformRole entity.
func (_u *PlatformRoleUpdateOne) Save(ctx context.Context) (*PlatformRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformRoleUpdateOne) SaveX(ctx context.Context) *PlatformRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := platformrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := platformrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PlatformRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := platformrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlatformRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformRoleUpdateOne) sqlSave(ctx context.Context) (_node *PlatformRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformrole.Table, platformrole.Columns, sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlatformRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformrole.FieldID)
		for _, f := range fields {
			if !platformrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platformrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(platformrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platformrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuper(); ok {
		_spec.SetField(platformrole.FieldIsSuper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(platformrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(platformrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platformrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.PermissionsTable,
			Columns: []string{platformrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platformrole.UsersTable,
			Columns: []string{platformrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformuserrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlatformRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
