// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformuserrole"
)

// PlatformUserRole is the model entity for the PlatformUserRole schema.
type PlatformUserRole struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uuid.UUID `json:"id,omitempty"`
	// 用户ID（users 表）
	UserID uuid.UUID `json:"user_id,omitempty"`
	// 平台角色ID
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlatformUserRoleQuery when eager-loading is set.
	Edges        PlatformUserRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlatformUserRoleEdges holds the relations/edges for other nodes in the graph.
type PlatformUserRoleEdges struct {
	// Role holds the value of the role edge.
	Role *PlatformRole `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlatformUserRoleEdges) RoleOrErr() (*PlatformRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: platformrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformUserRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformuserrole.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case platformuserrole.FieldID, platformuserrole.FieldUserID, platformuserrole.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformUserRole fields.
func (_m *PlatformUserRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformuserrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case platformuserrole.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case platformuserrole.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case platformuserrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlatformUserRole.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformUserRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the PlatformUserRole entity.
func (_m *PlatformUserRole) QueryRole() *PlatformRoleQuery {
	return NewPlatformUserRoleClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this PlatformUserRole.
// Note that you need to call PlatformUserRole.Unwrap() before calling this method if this PlatformUserRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformUserRole) Update() *PlatformUserRoleUpdateOne {
	return NewPlatformUserRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformUserRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformUserRole) Unwrap() *PlatformUserRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlatformUserRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformUserRole) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformUserRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlatformUserRoles is a parsable slice of PlatformUserRole.
type PlatformUserRoles []*PlatformUserRole
