// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrolepermission"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
)

// PlatformRolePermissionUpdate is the builder for updating PlatformRolePermission entities.
type PlatformRolePermissionUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformRolePermissionMutation
}

// Where appends a list predicates to the PlatformRolePermissionUpdate builder.
func (_u *PlatformRolePermissionUpdate) Where(ps ...predicate.PlatformRolePermission) *PlatformRolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *PlatformRolePermissionUpdate) SetRoleID(v uuid.UUID) *PlatformRolePermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PlatformRolePermissionUpdate) SetNillableRoleID(v *uuid.UUID) *PlatformRolePermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *PlatformRolePermissionUpdate) SetPermissionID(v uuid.UUID) *PlatformRolePermissionUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *PlatformRolePermissionUpdate) SetNillablePermissionID(v *uuid.UUID) *PlatformRolePermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the PlatformRole entity.
func (_u *PlatformRolePermissionUpdate) SetRole(v *PlatformRole) *PlatformRolePermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PlatformRolePermissionMutation object of the builder.
func (_u *PlatformRolePermissionUpdate) Mutation() *PlatformRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the PlatformRole entity.
func (_u *PlatformRolePermissionUpdate) ClearRole() *PlatformRolePermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformRolePermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformRolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformRolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformRolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformRolePermissionUpdate) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlatformRolePermission.role"`)
	}
	return nil
}

func (_u *PlatformRolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformrolepermission.Table, platformrolepermission.Columns, sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(platformrolepermission.FieldPermissionID, field.TypeUUID, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformrolepermission.RoleTable,
			Columns: []string{platformrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformrolepermission.RoleTable,
			Columns: []string{platformrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformRolePermissionUpdateOne is the builder for updating a single PlatformRolePermission entity.
type PlatformRolePermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformRolePermissionMutation
}

// SetRoleID sets the "role_id" field.
func (_u *PlatformRolePermissionUpdateOne) SetRoleID(v uuid.UUID) *PlatformRolePermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *PlatformRolePermissionUpdateOne) SetNillableRoleID(v *uuid.UUID) *PlatformRolePermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *PlatformRolePermissionUpdateOne) SetPermissionID(v uuid.UUID) *PlatformRolePermissionUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *PlatformRolePermissionUpdateOne) SetNillablePermissionID(v *uuid.UUID) *PlatformRolePermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the PlatformRole entity.
func (_u *PlatformRolePermissionUpdateOne) SetRole(v *PlatformRole) *PlatformRolePermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the PlatformRolePermissionMutation object of the builder.
func (_u *PlatformRolePermissionUpdateOne) Mutation() *PlatformRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the PlatformRole entity.
func (_u *PlatformRolePermissionUpdateOne) ClearRole() *PlatformRolePermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the PlatformRolePermissionUpdate builder.
func (_u *PlatformRolePermissionUpdateOne) Where(ps ...predicate.PlatformRolePermission) *PlatformRolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformRolePermissionUpdateOne) Select(field string, fields ...string) *PlatformRolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlatformRolePermission entity.
func (_u *PlatformRolePermissionUpdateOne) Save(ctx context.Context) (*PlatformRolePermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformRolePermissionUpdateOne) SaveX(ctx context.Context) *PlatformRolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformRolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformRolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformRolePermissionUpdateOne) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlatformRolePermission.role"`)
	}
	return nil
}

func (_u *PlatformRolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *PlatformRolePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platformrolepermission.Table, platformrolepermission.Columns, sqlgraph.NewFieldSpec(platformrolepermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlatformRolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platformrolepermission.FieldID)
		for _, f := range fields {
			if !platformrolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platformrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(platformrolepermission.FieldPermissionID, field.TypeUUID, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformrolepermission.RoleTable,
			Columns: []string{platformrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   platformrolepermission.RoleTable,
			Columns: []string{platformrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platformrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlatformRolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platformrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
