// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/platformrole"
)

// PlatformRole is the model entity for the PlatformRole schema.
type PlatformRole struct {
	config `json:"-"`
	// ID of the ent.
	// 角色ID
	ID uuid.UUID `json:"id,omitempty"`
	// 平台角色编码，如 super_admin / ops / auditor
	Code string `json:"code,omitempty"`
	// 角色展示名
	Name string `json:"name,omitempty"`
	// 是否超管；命中即全通，免权限点校验
	IsSuper bool `json:"is_super,omitempty"`
	// 角色描述
	Description string `json:"description,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlatformRoleQuery when eager-loading is set.
	Edges        PlatformRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlatformRoleEdges holds the relations/edges for other nodes in the graph.
type PlatformRoleEdges struct {
	// Permissions holds the value of the permissions edge.
	Permissions []*PlatformRolePermission `json:"permissions,omitempty"`
	// Users holds the value of the users edge.
	Users []*PlatformUserRole `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e PlatformRoleEdges) PermissionsOrErr() ([]*PlatformRolePermission, error) {
	if e.loadedTypes[0] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e PlatformRoleEdges) UsersOrErr() ([]*PlatformUserRole, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformrole.FieldIsSuper:
			values[i] = new(sql.NullBool)
		case platformrole.FieldCode, platformrole.FieldName, platformrole.FieldDescription:
			values[i] = new(sql.NullString)
		case platformrole.FieldCreatedAt, platformrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case platformrole.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformRole fields.
func (_m *PlatformRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case platformrole.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case platformrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case platformrole.FieldIsSuper:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_super", values[i])
			} else if value.Valid {
				_m.IsSuper = value.Bool
			}
		case platformrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case platformrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case platformrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlatformRole.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermissions queries the "permissions" edge of the PlatformRole entity.
func (_m *PlatformRole) QueryPermissions() *PlatformRolePermissionQuery {
	return NewPlatformRoleClient(_m.config).QueryPermissions(_m)
}

// QueryUsers queries the "users" edge of the PlatformRole entity.
func (_m *PlatformRole) QueryUsers() *PlatformUserRoleQuery {
	return NewPlatformRoleClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this PlatformRole.
// Note that you need to call PlatformRole.Unwrap() before calling this method if this PlatformRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformRole) Update() *PlatformRoleUpdateOne {
	return NewPlatformRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformRole) Unwrap() *PlatformRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlatformRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformRole) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("is_super=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSuper))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlatformRoles is a parsable slice of PlatformRole.
type PlatformRoles []*PlatformRole
