// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenant"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantnamespace"
)

// TenantNamespaceUpdate is the builder for updating TenantNamespace entities.
type TenantNamespaceUpdate struct {
	config
	hooks    []Hook
	mutation *TenantNamespaceMutation
}

// Where appends a list predicates to the TenantNamespaceUpdate builder.
func (_u *TenantNamespaceUpdate) Where(ps ...predicate.TenantNamespace) *TenantNamespaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantNamespaceUpdate) SetTenantID(v uuid.UUID) *TenantNamespaceUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantNamespaceUpdate) SetNillableTenantID(v *uuid.UUID) *TenantNamespaceUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *TenantNamespaceUpdate) SetNamespace(v string) *TenantNamespaceUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *TenantNamespaceUpdate) SetNillableNamespace(v *string) *TenantNamespaceUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantNamespaceUpdate) SetTenant(v *Tenant) *TenantNamespaceUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantNamespaceMutation object of the builder.
func (_u *TenantNamespaceUpdate) Mutation() *TenantNamespaceMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantNamespaceUpdate) ClearTenant() *TenantNamespaceUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantNamespaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantNamespaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantNamespaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantNamespaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantNamespaceUpdate) check() error {
	if v, ok := _u.mutation.Namespace(); ok {
		if err := tenantnamespace.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "TenantNamespace.namespace": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantNamespace.tenant"`)
	}
	return nil
}

func (_u *TenantNamespaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantnamespace.Table, tenantnamespace.Columns, sqlgraph.NewFieldSpec(tenantnamespace.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(tenantnamespace.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantnamespace.TenantTable,
			Columns: []string{tenantnamespace.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantnamespace.TenantTable,
			Columns: []string{tenantnamespace.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantnamespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantNamespaceUpdateOne is the builder for updating a single TenantNamespace entity.
type TenantNamespaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantNamespaceMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantNamespaceUpdateOne) SetTenantID(v uuid.UUID) *TenantNamespaceUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantNamespaceUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantNamespaceUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *TenantNamespaceUpdateOne) SetNamespace(v string) *TenantNamespaceUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *TenantNamespaceUpdateOne) SetNillableNamespace(v *string) *TenantNamespaceUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantNamespaceUpdateOne) SetTenant(v *Tenant) *TenantNamespaceUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantNamespaceMutation object of the builder.
func (_u *TenantNamespaceUpdateOne) Mutation() *TenantNamespaceMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantNamespaceUpdateOne) ClearTenant() *TenantNamespaceUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the TenantNamespaceUpdate builder.
func (_u *TenantNamespaceUpdateOne) Where(ps ...predicate.TenantNamespace) *TenantNamespaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantNamespaceUpdateOne) Select(field string, fields ...string) *TenantNamespaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantNamespace entity.
func (_u *TenantNamespaceUpdateOne) Save(ctx context.Context) (*TenantNamespace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantNamespaceUpdateOne) SaveX(ctx context.Context) *TenantNamespace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantNamespaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantNamespaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantNamespaceUpdateOne) check() error {
	if v, ok := _u.mutation.Namespace(); ok {
		if err := tenantnamespace.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "TenantNamespace.namespace": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantNamespace.tenant"`)
	}
	return nil
}

func (_u *TenantNamespaceUpdateOne) sqlSave(ctx context.Context) (_node *TenantNamespace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantnamespace.Table, tenantnamespace.Columns, sqlgraph.NewFieldSpec(tenantnamespace.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantNamespace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantnamespace.FieldID)
		for _, f := range fields {
			if !tenantnamespace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantnamespace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(tenantnamespace.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantnamespace.TenantTable,
			Columns: []string{tenantnamespace.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantnamespace.TenantTable,
			Columns: []string{tenantnamespace.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantNamespace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantnamespace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
