// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenant"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantnamespace"
)

// TenantNamespaceCreate is the builder for creating a TenantNamespace entity.
type TenantNamespaceCreate struct {
	config
	mutation *TenantNamespaceMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantNamespaceCreate) SetTenantID(v uuid.UUID) *TenantNamespaceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *TenantNamespaceCreate) SetNamespace(v string) *TenantNamespaceCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantNamespaceCreate) SetCreatedAt(v time.Time) *TenantNamespaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantNamespaceCreate) SetNillableCreatedAt(v *time.Time) *TenantNamespaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantNamespaceCreate) SetID(v uuid.UUID) *TenantNamespaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TenantNamespaceCreate) SetNillableID(v *uuid.UUID) *TenantNamespaceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *TenantNamespaceCreate) SetTenant(v *Tenant) *TenantNamespaceCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the TenantNamespaceMutation object of the builder.
func (_c *TenantNamespaceCreate) Mutation() *TenantNamespaceMutation {
	return _c.mutation
}

// Save creates the TenantNamespace in the database.
func (_c *TenantNamespaceCreate) Save(ctx context.Context) (*TenantNamespace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantNamespaceCreate) SaveX(ctx context.Context) *TenantNamespace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantNamespaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantNamespaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantNamespaceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantnamespace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tenantnamespace.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantNamespaceCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantNamespace.tenant_id"`)}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "TenantNamespace.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := tenantnamespace.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "TenantNamespace.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantNamespace.created_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "TenantNamespace.tenant"`)}
	}
	return nil
}

func (_c *TenantNamespaceCreate) sqlSave(ctx context.Context) (*TenantNamespace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantNamespaceCreate) createSpec() (*TenantNamespace, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantNamespace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantnamespace.Table, sqlgraph.NewFieldSpec(tenantnamespace.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(tenantnamespace.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantnamespace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantnamespace.TenantTable,
			Columns: []string{tenantnamespace.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantNamespaceCreateBulk is the builder for creating many TenantNamespace entities in bulk.
type TenantNamespaceCreateBulk struct {
	config
	err      error
	builders []*TenantNamespaceCreate
}

// Save creates the TenantNamespace entities in the database.
func (_c *TenantNamespaceCreateBulk) Save(ctx context.Context) ([]*TenantNamespace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantNamespace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantNamespaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantNamespaceCreateBulk) SaveX(ctx context.Context) []*TenantNamespace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantNamespaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantNamespaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
