// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrolepermission"
)

// TenantRolePermission is the model entity for the TenantRolePermission schema.
type TenantRolePermission struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uuid.UUID `json:"id,omitempty"`
	// 租户角色ID
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// 权限点ID
	PermissionID uuid.UUID `json:"permission_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantRolePermissionQuery when eager-loading is set.
	Edges        TenantRolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantRolePermissionEdges holds the relations/edges for other nodes in the graph.
type TenantRolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *TenantRole `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantRolePermissionEdges) RoleOrErr() (*TenantRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenantrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantRolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantrolepermission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tenantrolepermission.FieldID, tenantrolepermission.FieldRoleID, tenantrolepermission.FieldPermissionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantRolePermission fields.
func (_m *TenantRolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantrolepermission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tenantrolepermission.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case tenantrolepermission.FieldPermissionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value != nil {
				_m.PermissionID = *value
			}
		case tenantrolepermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantRolePermission.
// This includes values selected through modifiers, order, etc.
func (_m *TenantRolePermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the TenantRolePermission entity.
func (_m *TenantRolePermission) QueryRole() *TenantRoleQuery {
	return NewTenantRolePermissionClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this TenantRolePermission.
// Note that you need to call TenantRolePermission.Unwrap() before calling this method if this TenantRolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantRolePermission) Update() *TenantRolePermissionUpdateOne {
	return NewTenantRolePermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantRolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantRolePermission) Unwrap() *TenantRolePermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantRolePermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantRolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("TenantRolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenantRolePermissions is a parsable slice of TenantRolePermission.
type TenantRolePermissions []*TenantRolePermission
