// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenant"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantnamespace"
)

// TenantNamespace is the model entity for the TenantNamespace schema.
type TenantNamespace struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID uuid.UUID `json:"id,omitempty"`
	// 所属租户ID
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// K8s namespace 名；"*" 表示租户持有全部 namespace
	Namespace string `json:"namespace,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantNamespaceQuery when eager-loading is set.
	Edges        TenantNamespaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantNamespaceEdges holds the relations/edges for other nodes in the graph.
type TenantNamespaceEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantNamespaceEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantNamespace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantnamespace.FieldNamespace:
			values[i] = new(sql.NullString)
		case tenantnamespace.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tenantnamespace.FieldID, tenantnamespace.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantNamespace fields.
func (_m *TenantNamespace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantnamespace.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tenantnamespace.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case tenantnamespace.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case tenantnamespace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantNamespace.
// This includes values selected through modifiers, order, etc.
func (_m *TenantNamespace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the TenantNamespace entity.
func (_m *TenantNamespace) QueryTenant() *TenantQuery {
	return NewTenantNamespaceClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this TenantNamespace.
// Note that you need to call TenantNamespace.Unwrap() before calling this method if this TenantNamespace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantNamespace) Update() *TenantNamespaceUpdateOne {
	return NewTenantNamespaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantNamespace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantNamespace) Unwrap() *TenantNamespace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantNamespace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantNamespace) String() string {
	var builder strings.Builder
	builder.WriteString("TenantNamespace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenantNamespaces is a parsable slice of TenantNamespace.
type TenantNamespaces []*TenantNamespace
