// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/predicate"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenant"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrolepermission"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantuser"
)

// TenantRoleUpdate is the builder for updating TenantRole entities.
type TenantRoleUpdate struct {
	config
	hooks    []Hook
	mutation *TenantRoleMutation
}

// Where appends a list predicates to the TenantRoleUpdate builder.
func (_u *TenantRoleUpdate) Where(ps ...predicate.TenantRole) *TenantRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantRoleUpdate) SetTenantID(v uuid.UUID) *TenantRoleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantRoleUpdate) SetNillableTenantID(v *uuid.UUID) *TenantRoleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantRoleUpdate) SetCode(v string) *TenantRoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantRoleUpdate) SetNillableCode(v *string) *TenantRoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantRoleUpdate) SetName(v string) *TenantRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantRoleUpdate) SetNillableName(v *string) *TenantRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *TenantRoleUpdate) SetIsDefault(v bool) *TenantRoleUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *TenantRoleUpdate) SetNillableIsDefault(v *bool) *TenantRoleUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantRoleUpdate) SetDescription(v string) *TenantRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantRoleUpdate) SetNillableDescription(v *string) *TenantRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantRoleUpdate) ClearDescription() *TenantRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantRoleUpdate) SetUpdatedAt(v time.Time) *TenantRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantRoleUpdate) SetTenant(v *Tenant) *TenantRoleUpdate {
	return _u.SetTenantID(v.ID)
}

// AddPermissionIDs adds the "permissions" edge to the TenantRolePermission entity by IDs.
func (_u *TenantRoleUpdate) AddPermissionIDs(ids ...uuid.UUID) *TenantRoleUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the TenantRolePermission entity.
func (_u *TenantRoleUpdate) AddPermissions(v ...*TenantRolePermission) *TenantRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserIDs adds the "users" edge to the TenantUser entity by IDs.
func (_u *TenantRoleUpdate) AddUserIDs(ids ...uuid.UUID) *TenantRoleUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the TenantUser entity.
func (_u *TenantRoleUpdate) AddUsers(v ...*TenantUser) *TenantRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the TenantRoleMutation object of the builder.
func (_u *TenantRoleUpdate) Mutation() *TenantRoleMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantRoleUpdate) ClearTenant() *TenantRoleUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearPermissions clears all "permissions" edges to the TenantRolePermission entity.
func (_u *TenantRoleUpdate) ClearPermissions() *TenantRoleUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to TenantRolePermission entities by IDs.
func (_u *TenantRoleUpdate) RemovePermissionIDs(ids ...uuid.UUID) *TenantRoleUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to TenantRolePermission entities.
func (_u *TenantRoleUpdate) RemovePermissions(v ...*TenantRolePermission) *TenantRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUsers clears all "users" edges to the TenantUser entity.
func (_u *TenantRoleUpdate) ClearUsers() *TenantRoleUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to TenantUser entities by IDs.
func (_u *TenantRoleUpdate) RemoveUserIDs(ids ...uuid.UUID) *TenantRoleUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to TenantUser entities.
func (_u *TenantRoleUpdate) RemoveUsers(v ...*TenantUser) *TenantRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantRoleUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := tenantrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TenantRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tenantrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TenantRole.name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantRole.tenant"`)
	}
	return nil
}

func (_u *TenantRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantrole.Table, tenantrole.Columns, sqlgraph.NewFieldSpec(tenantrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenantrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenantrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(tenantrole.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenantrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenantrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantrole.TenantTable,
			Columns: []string{tenantrole.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantrole.TenantTable,
			Columns: []string{tenantrole.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantRoleUpdateOne is the builder for updating a single TenantRole entity.
type TenantRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantRoleMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantRoleUpdateOne) SetTenantID(v uuid.UUID) *TenantRoleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantRoleUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantRoleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantRoleUpdateOne) SetCode(v string) *TenantRoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantRoleUpdateOne) SetNillableCode(v *string) *TenantRoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantRoleUpdateOne) SetName(v string) *TenantRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantRoleUpdateOne) SetNillableName(v *string) *TenantRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *TenantRoleUpdateOne) SetIsDefault(v bool) *TenantRoleUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *TenantRoleUpdateOne) SetNillableIsDefault(v *bool) *TenantRoleUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantRoleUpdateOne) SetDescription(v string) *TenantRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantRoleUpdateOne) SetNillableDescription(v *string) *TenantRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TenantRoleUpdateOne) ClearDescription() *TenantRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantRoleUpdateOne) SetUpdatedAt(v time.Time) *TenantRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantRoleUpdateOne) SetTenant(v *Tenant) *TenantRoleUpdateOne {
	return _u.SetTenantID(v.ID)
}

// AddPermissionIDs adds the "permissions" edge to the TenantRolePermission entity by IDs.
func (_u *TenantRoleUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *TenantRoleUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the TenantRolePermission entity.
func (_u *TenantRoleUpdateOne) AddPermissions(v ...*TenantRolePermission) *TenantRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserIDs adds the "users" edge to the TenantUser entity by IDs.
func (_u *TenantRoleUpdateOne) AddUserIDs(ids ...uuid.UUID) *TenantRoleUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the TenantUser entity.
func (_u *TenantRoleUpdateOne) AddUsers(v ...*TenantUser) *TenantRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the TenantRoleMutation object of the builder.
func (_u *TenantRoleUpdateOne) Mutation() *TenantRoleMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantRoleUpdateOne) ClearTenant() *TenantRoleUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearPermissions clears all "permissions" edges to the TenantRolePermission entity.
func (_u *TenantRoleUpdateOne) ClearPermissions() *TenantRoleUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to TenantRolePermission entities by IDs.
func (_u *TenantRoleUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *TenantRoleUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to TenantRolePermission entities.
func (_u *TenantRoleUpdateOne) RemovePermissions(v ...*TenantRolePermission) *TenantRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUsers clears all "users" edges to the TenantUser entity.
func (_u *TenantRoleUpdateOne) ClearUsers() *TenantRoleUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to TenantUser entities by IDs.
func (_u *TenantRoleUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *TenantRoleUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to TenantUser entities.
func (_u *TenantRoleUpdateOne) RemoveUsers(v ...*TenantUser) *TenantRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the TenantRoleUpdate builder.
func (_u *TenantRoleUpdateOne) Where(ps ...predicate.TenantRole) *TenantRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantRoleUpdateOne) Select(field string, fields ...string) *TenantRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantRole entity.
func (_u *TenantRoleUpdateOne) Save(ctx context.Context) (*TenantRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantRoleUpdateOne) SaveX(ctx context.Context) *TenantRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := tenantrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TenantRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tenantrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TenantRole.name": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantRole.tenant"`)
	}
	return nil
}

func (_u *TenantRoleUpdateOne) sqlSave(ctx context.Context) (_node *TenantRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantrole.Table, tenantrole.Columns, sqlgraph.NewFieldSpec(tenantrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantrole.FieldID)
		for _, f := range fields {
			if !tenantrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenantrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenantrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(tenantrole.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenantrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tenantrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantrole.TenantTable,
			Columns: []string{tenantrole.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantrole.TenantTable,
			Columns: []string{tenantrole.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.PermissionsTable,
			Columns: []string{tenantrole.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenantrole.UsersTable,
			Columns: []string{tenantrole.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
