// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrole"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrolepermission"
)

// TenantRolePermissionCreate is the builder for creating a TenantRolePermission entity.
type TenantRolePermissionCreate struct {
	config
	mutation *TenantRolePermissionMutation
	hooks    []Hook
}

// SetRoleID sets the "role_id" field.
func (_c *TenantRolePermissionCreate) SetRoleID(v uuid.UUID) *TenantRolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *TenantRolePermissionCreate) SetPermissionID(v uuid.UUID) *TenantRolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantRolePermissionCreate) SetCreatedAt(v time.Time) *TenantRolePermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantRolePermissionCreate) SetNillableCreatedAt(v *time.Time) *TenantRolePermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantRolePermissionCreate) SetID(v uuid.UUID) *TenantRolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TenantRolePermissionCreate) SetNillableID(v *uuid.UUID) *TenantRolePermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRole sets the "role" edge to the TenantRole entity.
func (_c *TenantRolePermissionCreate) SetRole(v *TenantRole) *TenantRolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the TenantRolePermissionMutation object of the builder.
func (_c *TenantRolePermissionCreate) Mutation() *TenantRolePermissionMutation {
	return _c.mutation
}

// Save creates the TenantRolePermission in the database.
func (_c *TenantRolePermissionCreate) Save(ctx context.Context) (*TenantRolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantRolePermissionCreate) SaveX(ctx context.Context) *TenantRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantRolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantRolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantRolePermissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantrolepermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tenantrolepermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantRolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "TenantRolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "TenantRolePermission.permission_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantRolePermission.created_at"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "TenantRolePermission.role"`)}
	}
	return nil
}

func (_c *TenantRolePermissionCreate) sqlSave(ctx context.Context) (*TenantRolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantRolePermissionCreate) createSpec() (*TenantRolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantRolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantrolepermission.Table, sqlgraph.NewFieldSpec(tenantrolepermission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(tenantrolepermission.FieldPermissionID, field.TypeUUID, value)
		_node.PermissionID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantrolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantrolepermission.RoleTable,
			Columns: []string{tenantrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantRolePermissionCreateBulk is the builder for creating many TenantRolePermission entities in bulk.
type TenantRolePermissionCreateBulk struct {
	config
	err      error
	builders []*TenantRolePermissionCreate
}

// Save creates the TenantRolePermission entities in the database.
func (_c *TenantRolePermissionCreateBulk) Save(ctx context.Context) ([]*TenantRolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantRolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantRolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantRolePermissionCreateBulk) SaveX(ctx context.Context) []*TenantRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantRolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantRolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
