// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenant"
	"github.com/lvyanru/dac-apiserver/internal/ent/tenantrole"
)

// TenantRole is the model entity for the TenantRole schema.
type TenantRole struct {
	config `json:"-"`
	// ID of the ent.
	// 角色ID
	ID uuid.UUID `json:"id,omitempty"`
	// 所属租户ID
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// 角色编码，(tenant_id, code) 唯一
	Code string `json:"code,omitempty"`
	// 角色展示名
	Name string `json:"name,omitempty"`
	// 新成员未指定角色时的默认角色
	IsDefault bool `json:"is_default,omitempty"`
	// 角色描述
	Description string `json:"description,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantRoleQuery when eager-loading is set.
	Edges        TenantRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantRoleEdges holds the relations/edges for other nodes in the graph.
type TenantRoleEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Permissions holds the value of the permissions edge.
	Permissions []*TenantRolePermission `json:"permissions,omitempty"`
	// Users holds the value of the users edge.
	Users []*TenantUser `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantRoleEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e TenantRoleEdges) PermissionsOrErr() ([]*TenantRolePermission, error) {
	if e.loadedTypes[1] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e TenantRoleEdges) UsersOrErr() ([]*TenantUser, error) {
	if e.loadedTypes[2] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantrole.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case tenantrole.FieldCode, tenantrole.FieldName, tenantrole.FieldDescription:
			values[i] = new(sql.NullString)
		case tenantrole.FieldCreatedAt, tenantrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case tenantrole.FieldID, tenantrole.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantRole fields.
func (_m *TenantRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tenantrole.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case tenantrole.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case tenantrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tenantrole.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case tenantrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case tenantrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tenantrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantRole.
// This includes values selected through modifiers, order, etc.
func (_m *TenantRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the TenantRole entity.
func (_m *TenantRole) QueryTenant() *TenantQuery {
	return NewTenantRoleClient(_m.config).QueryTenant(_m)
}

// QueryPermissions queries the "permissions" edge of the TenantRole entity.
func (_m *TenantRole) QueryPermissions() *TenantRolePermissionQuery {
	return NewTenantRoleClient(_m.config).QueryPermissions(_m)
}

// QueryUsers queries the "users" edge of the TenantRole entity.
func (_m *TenantRole) QueryUsers() *TenantUserQuery {
	return NewTenantRoleClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this TenantRole.
// Note that you need to call TenantRole.Unwrap() before calling this method if this TenantRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantRole) Update() *TenantRoleUpdateOne {
	return NewTenantRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantRole) Unwrap() *TenantRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantRole) String() string {
	var builder strings.Builder
	builder.WriteString("TenantRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenantRoles is a parsable slice of TenantRole.
type TenantRoles []*TenantRole
