apiVersion: dac.dac.io/v1alpha1
kind: DataDescriptor
metadata:
  name: dd01-mysql
  namespace: dac
  labels:
    app.kubernetes.io/name: execution-engine
    app.kubernetes.io/managed-by: kustomize
spec:
  descriptorType: "structured-mysql"
  sources:
    - type: mysql
      name: "mysql-production"
      metadata:
        host: "mysql-server"
        port: "3306"
        user: "root"
        password: "123"
        database: "test1"
      extract:
        tables: []
      prompts:
        prompts:
          name: ""
      processing:
        cleaning:
          - rule: "remove_duplicates"
            params: 
              fields: "user_id,timestamp"
          - rule: "fill_missing"
            params: 
              field: "price"
              value: "0"
      classification:
        - domain: "科学技术类"
          category: "计算机科学与技术"
          subcategory: "软件工程师"
          tags:
            - skill: ["编程", "算法"]
            - industry: ["互联网"]