# stage 1
# Build stage with explicit platform specification
FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/python:3.13-ubuntu-timezone-amd64 AS uv

# Install the project into /app
WORKDIR /app

RUN mkdir /app/sdks

COPY sdks/model_sdk-0.1.0-py3-none-any.whl /app/sdks/model_sdk-0.1.0-py3-none-any.whl

COPY sdks/vector_sdk-0.1.0-py3-none-any.whl /app/sdks/vector_sdk-0.1.0-py3-none-any.whl

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
ADD . /app
RUN uv sync --frozen --no-dev --no-editable


# stage 2
FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/python:3.13-ubuntu-timezone-amd64

COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT ["data-services", "--port", "8000"]