# Build stage with explicit platform specification
#FROM ghcr.io/astral-sh/uv:python3.13-alpine AS uv

FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/uv:python3.13-alpine-amd64 AS uv

# Install the project into /app
WORKDIR /app

RUN mkdir /app/sdks

COPY sdks/model_sdk-0.1.0-py3-none-any.whl /app/sdks/model_sdk-0.1.0-py3-none-any.whl

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
ADD . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-editable

# Final stage with explicit platform specification
#FROM docker.m.daocloud.io/python:3.13-alpine

FROM registry.cn-shanghai.aliyuncs.com/jamesxiong/python:3.13-alpine-timezone-amd64

COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

COPY agent_card /app/agent_card

RUN rm -fr /app/.venv/lib/python3.13/site-packages/a2a/utils/telemetry.py

COPY telemetry.py /app/.venv/lib/python3.13/site-packages/a2a/utils/telemetry.py

ENTRYPOINT ["agent", "--port", "10100"]